services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: project2_api
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - shared_net

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: project2_streamlit
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - shared_net

networks:
  shared_net:
    external: true