"""initial schema

Revision ID: a5f3bf693c80
Revises: 
Create Date: 2026-01-26 15:32:40.657535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5f3bf693c80'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_inputs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('steps_n', sa.Integer(), nullable=True),
    sa.Column('proteins_g', sa.Integer(), nullable=True),
    sa.Column('kcal_in', sa.Integer(), nullable=True),
    sa.Column('kcal_junk_in', sa.Integer(), nullable=True),
    sa.Column('kcal_out_training', sa.Integer(), nullable=True),
    sa.Column('stress_rel', sa.Integer(), nullable=True),
    sa.Column('sleep_hours', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('waist_cm', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', name='uq_daily_inputs_date')
    )
    op.create_table('daily_kpis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('kcal_out_total', sa.Float(), nullable=True),
    sa.Column('balance_kcal', sa.Float(), nullable=True),
    sa.Column('balance_7d_average', sa.Float(), nullable=True),
    sa.Column('protein_per_kg', sa.Float(), nullable=True),
    sa.Column('healthy_food_pct', sa.Float(), nullable=True),
    sa.Column('adherence_steps', sa.Integer(), nullable=True),
    sa.Column('weight_7d_avg', sa.Float(), nullable=True),
    sa.Column('waist_change_7d', sa.Float(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', name='uq_daily_kpis_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_kpis')
    op.drop_table('daily_inputs')
    # ### end Alembic commands ###
